### ISSUE TITLE
DynamoDB Local failed to start with code 1

### ISSUE THREAD

**Issue by fishcharlie** [99xt/dynamodb-localhost#5]
I keep getting this error for some reason. Doesn't give too much detail about what exactly happened. Any ideas?

```
DynamoDB Local failed to start with code 1
{ Error: connect ECONNREFUSED 127.0.0.1:8000
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  message: 'connect ECONNREFUSED 127.0.0.1:8000',
  code: 'NetworkingError',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8000,
  region: 'us-west-2',
  hostname: 'localhost',
  retryable: true,
  time: 2016-09-13T03:26:05.804Z }
```

**Comment by AshanFernando** [comment]
@fishcharlie Dynamodb local is using port 8000 as the default port. Can you check whether, another application running in the same port? Also you can change the default port of dynamodb by adding the port attribute.

**Comment by fishcharlie** [comment]
So I've tried stopping DynamoDB local before starting it in my code and that seems to kinda have fixed the issue. For some reason it doesn't give me that error ECONNREFUSED but it still gives me DynamoDB Local failed to start with code 1 sometimes. No other error other then that.

Not sure what else could be running on that port. Also again sometimes happens with the code 1 and sometimes doesn't happen.

**Comment by AshanFernando** [comment]
Sometimes the DynamoDB process runs in the background if we directly closes the terminal. For those instances close the process manually using task manager and start the DynamoDB local again.
